package com.auro.application.core

object ConstantVariables {
    var onboarding1: String = "onboarding1"
    var onboarding2: String = "onboarding2"
    var createpin: String = "createpin"
    const val addNewChild = "addNewChild"
    const val isRegistration = "isRegistration"
    const val isLogout = "logout"

    const val LOGIN_WITH_OTP = "loginWithOtp"
    const val LOGIN_WITH_PIN = "loginWithPin"
    const val SIGNUP_PIN = "signupWithPin"
    const val FORGOT_PIN = "forgotPin"
    const val EDIT_MOBILE = "editMobile"
    const val FORGOT_PASSWORD = "forgotPassword"
    const val START_DATE = "startDate"
    const val END_DATE = "endDate"
    const val REFERRED_BY = "ReferredBy"
    const val REFERRED_USER_ID = "ReferredUserId"
    const val REFERRED_TYPE_ID = "ReferredTypeId"
    const val SELECTED_DATE = "selectedDate"
    const val PRACTICE_PAGE = "practicePage"
    const val ENTER_PASSWORD = "enterPassword"
    const val CONCEPT_SIZE = "ConceptSize"
    const val CONCEPT_ID = "ConceptId"
    const val CONCEPT_PRACTICE = "ConceptPractice"
    const val CONCEPT_Name = "ConceptName"
    const val PARENT_DASHBOARD = "parentDashboard"
    const val LOGIN = "login"
    const val LOGIN_WITH_PASSWORD = "loginWithPassword"
    const val PARTNER_NAME = "partnerName"


    // Shared Pref Constants
    const val USER_PIN = "userPin"
    const val USER_STUDENT_LIST = "userStudentList"
    const val USER_STUDENT_LIST_STUDENT = "USER_STUDENT_LIST_STUDENT"
    const val UPI_LIST_STUDENT = "UPI_LIST_STUDENT"
    const val USER_STUDENT_SUBJECT = "USER_STUDENT_SUBJECT"
    const val USER_ASSESSMENT_SAVE_QUESTION = "USER_ASSESSMENT_SAVE_QUESTION"
    const val STUDENT_KYC_DATA = "STUDENT_KYC_DATA"
    const val STUDENT_KYC_UPLOAD_DATA = "STUDENT_KYC_UPLOAD_DATA"
    const val USER_PROFILER_SAVE_LIST = "USER_PROFILER_SAVE_LIST"
    const val USER_STUDENT_PROFILE = "studentProfile"
    const val USER_PARENT_PROFILE = "ParentProfile"
    const val USER_LANGUAGE_TRANSLATION = "userTranslation"
    const val SELECTED_SUBJECT_DATA = "SELECTED_SUBJECT_DATA"
    const val SELECTED_CONCEPT_DATA = "SELECTED_CONCEPT_DATA"
    const val LANGUAGE_CODE = "LANGUAGE_CODE"
    const val EXAM_NAME = "EXAM_NAME"
    const val IS_PRACTICE = "IS_PRACTICE"
    const val CHILD_COUNT = "CHILD_COUNT"
    const val EXAM_ID = "EXAM_Id"
    const val EXAM_ASSESSMENT_ID = "EXAM_ASSESSMENT_ID"
    const val GET_QUIZ_RESULT = "GET_QUIZ_RESULT"
    const val SELECTED_BANK_UPI_DATA = "BankUpi"
    const val SELECTED_WALLET_DATA = "Wallet_Data"
    const val SELECTED_BANK_UPI = "bankUpi"
    const val SELECTED_BANK_UPI_DIRECTION = "bankUpiDirection"
    const val WALLET_AMOUNT = "walletAmount"
    const val TRANSACTION_ID = "TransactionId"
    const val TRANSACTION_DATE_TIME = "TransactionDateTime"
    const val TRANSACTION_AMOUNT = "TransactionAmount"
    const val TRANSACTION_STATUS = "TransactionStatus"
    const val isKYC = "Kyc"

}